### ISSUE TITLE
GPX file used not typical, what changes are  necessary to read  to read trackpoints

### ISSUE THREAD

**Issue by ogbsn** [Andrewwango/gpx-overpass-googlemaps-tutorial#1]
I have used this tutorial to generate a csx & gpx file of places along a route to read into basecamp.
it works very well with the pilgrims gpx file in the example, however most of my files use track points.

How could I change the command work with such a file ?

lines in question:

with open("inputtr.gpx") as f:
    points = [(point.latitude, point.longitude) for point in parse(f).routes[0].points]
    input_df = pd.DataFrame(points, columns=["latitude", "longitude"])

typical format of my gpx  files
   <?xml version="1.0" encoding="utf-8"?><gpx creator="Garmin Desktop App" version="1.1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd 
  <metadata>
    <link href="http://www.garmin.com">
      <text>Garmin International</text>
    </link>
    <time>2024-07-19T14:10:05Z</time>
    <bounds maxlat="52.356712175533175" maxlon="-1.572707472369075" minlat="52.336580520495772" minlon="-1.593480259180069" />
  </metadata>

  <trk>
    <name>track poins example</name>
    <extensions>
      <gpxx:TrackExtension>
        <gpxx:DisplayColor>DarkGray</gpxx:DisplayColor>
      </gpxx:TrackExtension>
    </extensions>
    <trkseg>
      <trkpt lat="52.356712175533175" lon="-1.593480259180069">
        <ele>87</ele>
      </trkpt>
      <trkpt lat="52.356612682342529" lon="-1.593446731567383">
        <ele>87.0625</ele>
      </trkpt>
      <trkpt lat="52.355818748474121" lon="-1.593317985534668">
        <ele>85.90625</ele>
      </trkpt>
      <trkpt lat="52.355432510375977" lon="-1.593210697174072">

**Comment by ogbsn** [comment]
<trkseg>
      <trkpt lat="52.356712175533175" lon="-1.593480259180069">
        <ele>87</ele>
      </trkpt>
      <trkpt lat="52.356612682342529" lon="-1.593446731567383">
        <ele>87.0625</ele>
      </trkpt>
      <trkpt lat="52.355818748474121" lon="-1.593317985534668">
        <ele>85.90625</ele>
      </trkpt>
      <trkpt lat="52.355432510375977" lon="-1.593210697174072">
        <ele>87.15625</ele>

**Comment by Rymez2K** [comment]
You can use:
`points = [(point.latitude, point.longitude) for point in parse(f).tracks[0].segments[0].points]`

**Comment by Andrewwango** [comment]
Track support is now in the blog using the code above. Tested with https://www.openstreetmap.org/trace/11446009/data

**Comment by Andrewwango** [comment]
Track support is now in the blog using the code above. Tested with https://www.openstreetmap.org/trace/11446009/data
